### PR TITLE
Implemented Image Denoising

### PR DESCRIPTION
**Pull request by kritika12298**
Single Image Denoising

### CODE REVIEW

**Comment by kritika12298** [comment]
Working on its script, till then you can have a look on Colab link provided in README.md @smaranjitghose

**Comment by smaranjitghose** [comment]
@kritika12298  Please provide access to all for the Colab notebook😅

**Comment by kritika12298** [comment]
Actually, I have always done my work on Jupyter Notebook and am very less
experienced with Colab.
Can you guide me on how can I make Colab link accessible to all.

**Comment by kritika12298** [comment]
I tried to Colab Notebook, please let me know if its correct @smaranjitghose

**Pull request closed without merging**
